---
- name: installation the packages 
  hosts: all
  become: true
  tasks:
  - name: Install nginx
    apt: name=nginx state=latest
  - name: Copy custom index.html
    copy:
       src: index.html
       dest: /var/www/html/index.html
       mode: '0644'
  - name: Start and enable service nginx 
    service:
       name: nginx 
       state: started
       enabled: yes 
   
